# Configuration for chart-releaser
owner: infnada
git-repo: k8s-network-policy-visualizer
charts-repo-url: https://github.com/infnada/k8s-network-policy-visualizer/releases/download
index-path: ./docs/index.yaml
packages-with-index: true
skip-existing: true
