name: Package and Release Helm Chart

on:
  push:
    branches: [ main ]
    paths:
      - 'helm/**'
      - '.github/workflows/helm-release.yml'
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
    paths:
      - 'helm/**'

jobs:
  lint-and-test:
    name: Lint and Test Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --charts helm/networkpolicy-visualizer

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        if: github.event_name != 'pull_request'

      - name: Run chart-testing (install)
        if: github.event_name != 'pull_request'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --charts helm/networkpolicy-visualizer

  release:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name != 'pull_request'
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm
          charts_repo_url: https://username.github.io/k8s-network-policy-visualizer
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
