name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate Code and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm test
